publishdir = "docs/"
static = "static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://aiea-lab.github.io"
canonifyurls = true
theme = "our-theme"
title = "AIEA Lab"
math = true
copyright = "&copy; AIEA Lab, 2023 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of the UCSC AIEA Lab"
  author = "Leilani H. Gilpin"
#  email = "mail@example.org"
  address = "UCSC - Santa Cruz, CA"

  slogan = "AIEA Lab at UCSC"
  slogan_text = "Artificial Intelligence Explainability Accountability (AIEA) Lab"

  [[params.slogan_columns]]
    title = "About"
    text =  "Aloha world! We are an interdisciplinary group of students and researchers focused at UC Santa Cruz.  "
    link = "/about"
    link_text = "Meet the team"
    weight = 1
  
  [[params.slogan_columns]]
    title = "Mission"
    text = "Our mission is to conduct cutting-edge interpretable and explainable AI research that inspires curiosity, while actively explaining systemic injustices within and outside computer science through *expanded empowerment*, alongside *fun and stimulating* collaborators."
    link = "/mission"
    link_text = "Read more"
    weight = 2

  [[params.slogan_columns]]
    title = "Approach"
    text = "The AIEA lab takes an interdisciplinary approach to understand complex AI systems.  We use existing explainable models, we develop models, and we test models.  Our group puts a strong focus on interpretability as a science, and we employ it in everything we do, including transparent meetings, feedback, and open-source code."
    link = "/approach"
    link_text = "Read more"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Join us section.
  [params.join]
    enable = true
    title = "Join us!"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 3

    [[menu.main]]
      name = "Projects"
      url = "/#projects"
      weight = 4

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/#posts"
      weight = 6

  [[menu.main]]
      name = "Join Us!"
      url = "/join"
      weight = 7


  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 8
