name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Deploy
        run: hugo 
      
