name: Build and Deploy Hugo Site from aiea-connect-notion

on:
  push:
    branches:
      - aiea-connect-notion-2
  pull_request:
    branches:
      - aiea-connect-notion-2
  schedule:
    - cron: '0 0 * * 0'  #Run the job every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: aiea-connect-notion-2  # Ensure the workflow checks out the aiea-connect-notion branch

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build Site
        run: hugo server
