name: Build and Deploy Hugo Site from aiea-connect-notion

on:
  push:
    branches:
      - aiea-connect-notion
  pull_request:
    branches:
      - aiea-connect-notion
  schedule:
    - cron: '0 0 * * *'  # Adjust cron as needed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: aiea-connect-notion  # Ensure the workflow checks out the aiea-connect-notion branch

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and Update Project Details
        run: python fetch-details.py

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.126.1/hugo_extended_0.126.1_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.126.1_Linux-64bit.deb

      - name: Build Site
        run: hugo -D

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch:  aiea-connect-notion
